############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Priorities"
url = "/priorities"
weight = 2

[[main]]
name = "Who We Are"
url = "/about"
weight = 3

[[main]]
weight = 4
name = "Get Involved"

[[main]]
parent = "Get Involved"
name = "Become a Supporter"
url = "/donate"

[[main]]
parent = "Get Involved"
name = "Sign up for our Newsletter"
url = "/newsletter"

# footer menu
[[footer]]
name = "Priorities"
url = "/priorities"
weight = 1

[[footer]]
name = "Who We Are"
url = "/about"
weight = 2
